backend:
  name: bitbucket
  repo: mmmcdev/prototype.mmmc.me # Path to your Github repository
  branch: master # Branch to update

publish_mode: editorial_workflow

media_folder: "static/img/uploads" # Media files will be stored in the repo under static/img/uploads
public_folder: "/img/uploads" # The src attribute for uploaded media will begin with /img/uploads
